#name: Deploy to Render
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      -
#
#      - name: Trigger Render Deploy Hook
#        run: |
#          curl -X POST https://api.render.com/deploy/srv-cscbgcggph6c73bq29o0?key=AH0ZtR1nafo

name: Deploy to Render and Update Site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Триггер развертывания на Render
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST https://api.render.com/deploy/srv-cscbgcggph6c73bq29o0?key=AH0ZtR1nafo

#      # 2. Клонирование репозитория сайта
#      - name: Checkout site repository
#        uses: actions/checkout@v3
#        with:
#          repository: Slipbang/webdev-basics
#          path: site
#
#      # 3. Копирование собранного сайта в папку dist
#      - name: Copy built site to dist
#        run: |
#          mkdir -p dist
#          cp -r site/public_webdevManual/* public_webdevManual/